# Generated by Django 5.1.1 on 2024-12-03 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место, в котором необходимо выполнять привычку",
                        max_length=50,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Установите время, когда необходимо выполнять привычку",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие, которое представляет собой привычка",
                        max_length=50,
                        verbose_name="Действие ",
                    ),
                ),
                (
                    "nice_habit",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Это привычка, которую можно привязать к выполнению полезной привычки?",
                        null=True,
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения привычки для напоминания в днях (по умолчанию ежедневная)",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, null=True, verbose_name="Вознаграждение"
                    ),
                ),
                (
                    "time_to_complete",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        null=True,
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "associted_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
